### PR TITLE
Hard coded service location into API calls, so things work on proxy

### PR DESCRIPTION
**Pull request by jondionowens**

### CODE REVIEW

**Comment by allenhsieh** [comment]
Hey Jonathan, I just saw this, is this a WIP or good to go?

**Comment by jondionowens** [comment]
This should be good to go

**Review by allenhsieh — APPROVED** [review]
Good catch on the '/1'

Did you see my note from the last PR about deleting/moving your example folder if you don't need it anymore?

**Comment by jondionowens** [comment]
Yo, yes I did see this. Will fix this now. Thanks man

**Pull request merged**
